chisq.test(Reason_for_absence, Month_of_absence)
chisq.test(Reason_for_absence, Day_of_the_week)
chisq.test(Reason_for_absence, Season)
summary(aov(TravelCost ~ Reason_for_absence))
summary(aov(CommuteDistance ~ Reason_for_absence))
summary(aov(YearsService ~ Reason_for_absence))
summary(aov(WorkLoad ~ Reason_for_absence))
summary(aov(Target ~ Reason_for_absence))
chisq.test(Reason_for_absence, Education)
chisq.test(Reason_for_absence, Children)
chisq.test(Reason_for_absence, Alcohol)
chisq.test(Reason_for_absence, Smoker)
chisq.test(Reason_for_absence, NoOfPets)
summary(aov(BodyWeight ~ Reason_for_absence))
chisq.test(Reason_for_absence, Absent)
